// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqB3xfyPD_SLRoQ3NmWTzDZyq4tO123Ok',
    appId: '1:1018143782668:web:8efde638246cfdad84fb29',
    messagingSenderId: '1018143782668',
    projectId: 'authtutorial-8075c',
    authDomain: 'authtutorial-8075c.firebaseapp.com',
    storageBucket: 'authtutorial-8075c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5_z1_Jsd1fTMdGjiP8gG4YIq5IhxmuM0',
    appId: '1:1018143782668:android:1c726f9acce38d3884fb29',
    messagingSenderId: '1018143782668',
    projectId: 'authtutorial-8075c',
    storageBucket: 'authtutorial-8075c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKYO1MQC2QjsnocJMqgCy8_UgwWI6JxoI',
    appId: '1:1018143782668:ios:7ebf1adf576e5f2984fb29',
    messagingSenderId: '1018143782668',
    projectId: 'authtutorial-8075c',
    storageBucket: 'authtutorial-8075c.firebasestorage.app',
    iosBundleId: 'com.example.currencyConvertor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKYO1MQC2QjsnocJMqgCy8_UgwWI6JxoI',
    appId: '1:1018143782668:ios:7ebf1adf576e5f2984fb29',
    messagingSenderId: '1018143782668',
    projectId: 'authtutorial-8075c',
    storageBucket: 'authtutorial-8075c.firebasestorage.app',
    iosBundleId: 'com.example.currencyConvertor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqB3xfyPD_SLRoQ3NmWTzDZyq4tO123Ok',
    appId: '1:1018143782668:web:dc0ecf607023ab6b84fb29',
    messagingSenderId: '1018143782668',
    projectId: 'authtutorial-8075c',
    authDomain: 'authtutorial-8075c.firebaseapp.com',
    storageBucket: 'authtutorial-8075c.firebasestorage.app',
  );
}
